name: Oracle Reply Bot

on:
  schedule:
    - cron: '0 14 * * *'    # 10:00 AM EST
    - cron: '17 15 * * *'   # 11:17 AM EST
    - cron: '33 16 * * *'   # 12:33 PM EST
    - cron: '5 18 * * *'    # 2:05 PM EST
    - cron: '41 19 * * *'   # 3:41 PM EST
    - cron: '9 21 * * *'    # 5:09 PM EST
    - cron: '26 22 * * *'   # 6:26 PM EST
    - cron: '55 23 * * *'   # 7:55 PM EST
    - cron: '13 1 * * *'    # 9:13 PM EST
    - cron: '45 3 * * *'    # 11:45 PM EST
  workflow_dispatch:

jobs:
  oracle-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Oracle reply API endpoint
        run: curl -X GET https://pun-bot-eta.vercel.app/api/reply-oracle


