name: Reply Oracle Bot

on:
  schedule:
    # Times are in UTC; EST = UTC-5 (standard) or UTC-4 (DST)
    # Assuming DST (UTC-4), 10:00 AM EST = 14:00 UTC, 23:30 EST = 03:30 UTC next day
    # Adjust these UTC times if your local DST changes or if you want fixed UTC times instead
    - cron: '0 14 * * *'    # 10:00 AM EST
    - cron: '30 15 * * *'   # 11:30 AM EST
    - cron: '0 17 * * *'    # 1:00 PM EST
    - cron: '30 18 * * *'   # 2:30 PM EST
    - cron: '0 20 * * *'    # 4:00 PM EST
    - cron: '30 21 * * *'   # 5:30 PM EST
    - cron: '0 23 * * *'    # 7:00 PM EST
    - cron: '30 0 * * *'    # 8:30 PM EST (next day UTC)
    - cron: '0 2 * * *'     # 10:00 PM EST (next day UTC)
    - cron: '30 3 * * *'    # 11:30 PM EST (next day UTC)

jobs:
  reply-oracle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Reply Oracle Bot
        run: node reply-bot/replyOraclebot.js --maxReplies=1
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
