name: Cron Tweet Pun

on:
  schedule:
    - cron: '0 14 * * *'  # 9:00 AM EST
    - cron: '0 20 * * *'  # 3:00 PM EST
    - cron: '0 2 * * *'   # 9:00 PM EST (which is 2 AM UTC next day)
  workflow_dispatch:

jobs:
  tweet-pun:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tweet-pun endpoint
        run: |
          curl -X GET https://pun-bot-eta.vercel.app/api/tweet-pun

