name: Cron Tweet Pun

on:
  schedule:
    - cron: '0 14-23 * * *'
    - cron: '0 0-3 * * *'
  workflow_dispatch:

jobs:
  tweet-pun:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tweet-pun endpoint
        run: |
          curl -X GET https://pun-bot-eta.vercel.app/api/tweet-pun

