name: Tweet Pun Bot

on:
  schedule:
    - cron: '0 13 * * *'   # 9:00 AM EST
    - cron: '0 16 * * *'   # 12:00 PM EST
    - cron: '0 19 * * *'   # 3:00 PM EST
    - cron: '0 23 * * *'   # 7:00 PM EST
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tweet-pun bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
        run: node tweet-bot/tweet-pun.js
